<a href="https://colab.research.google.com/github/julieklaessens-dotcom/data-analyst-formation/blob/main/Notebook_Python_NumPy%26Panda_Week_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semaine 3 — Notebook Python (Numpy & Pandas)

*Auteur :* Julie Klaessens  
*Date :* 2025-10-09  
*Objectif :* Découvrir comment optimiser son code à l'aide des deux bibliothèques Python les plus populaires : NumPy et pandas. Ces bibliothèques  permettent de programmer plus efficacement et de gagner du temps.

## 1. Introduction
Ce notebook compile mes exercices issus de **Dataquest (Introduction to Pandas and NumPy for Data Analysis)**.

## 2. Introduction to Pandas and NumPy for Data Analysis

###      2.1 Introduction to NumPy

In [ ]:
## 2. Introduction to Ndarrays ##

import numpy as np

data_ndarray = np.array([10, 20, 30])

## 4. NYC Taxi-Airport Data ##

from google.colab import drive
drive.mount('/content/drive')

import csv
import numpy as np

# import nyc_taxi.csv as a list of lists
f = open("/content/drive/MyDrive/Data/nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for element in row:
        converted_row.append(float(element))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment
taxi = np.array(converted_taxi_list)

## 5. Array Shapes ##

taxi_shape = np.shape(taxi) # ou taxi.shape
print(taxi_shape)

## 6. Selecting and Slicing Rows from Ndarrays ##

row_0 = taxi[0]
rows_391_to_500 = taxi[391:501]
row_21_column_5 = taxi[21,5]

## 7. Selecting Columns and Custom Slicing Ndarrays ##

columns_1_4_7 = taxi[:,[1,4,7]]
row_99_columns_5_to_8 = taxi[99,5:9]
rows_100_to_200_column_14 = taxi[100:201,14]

## 8. Vector Operations ##

fare_amount = taxi[:,9]
fees_amount = taxi[:,10]
fare_and_fees = fare_amount + fees_amount
print(fare_and_fees)

## 9. Vector Operations (Continued) ##

trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]
trip_length_hours = trip_length_seconds / 3600
trip_mph = trip_distance_miles / trip_length_hours
print(trip_mph[:10])

## 10. Calculating Statistics for 1D Ndarrays ##

mph_min = trip_mph.min()
mph_max = trip_mph.max()
print(mph_max)
mph_mean = trip_mph.mean()
print(mph_mean)

## 12. Calculating Statistics for 2D Ndarrays ##

# extract the first 5 rows only
taxi_first_five = taxi[:5]
# select columns: fare_amount, fees_amount, tolls_amount, and tip_amount
fare_components = taxi_first_five[:, 9:13]
fare_sums = fare_components.sum(axis=1)
fare_totals = taxi_first_five[:,13]
print(fare_totals)
print(fare_sums)

Mounted at /content/drive
(2013, 15)
[52.8 46.3 37.8 ... 52.8 35.8 49.3]
[37.11340206 38.58157895 31.27222982 25.88429752 26.3715415  38.53293413
 32.81553398 35.95075239 51.00702576 33.20207254]
82800.0
169.98315083655157
[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]


### 2.2 Boolean Indexing with NumPy

In [ ]:
## 1. Reading CSV files with NumPy ##

import numpy as np

taxi = np.genfromtxt("/content/drive/MyDrive/Data/nyc_taxis.csv", delimiter=',')
taxi_shape = taxi.shape

print(taxi)
print(taxi_shape)

## 2. Reading CSV Files with NumPy (Continued) ##

taxi = np.genfromtxt("/content/drive/MyDrive/Data/nyc_taxis.csv", delimiter=',')
taxi_header_removed = taxi[1:]
removed_shape = taxi_header_removed.shape

taxi_header_skipped = np.genfromtxt("/content/drive/MyDrive/Data/nyc_taxis.csv", delimiter=',', skip_header=1)
skipped_shape = taxi_header_skipped.shape

print("First 5 rows of taxi_header_removed:")
print(taxi_header_removed[:5])

print("\nFirst 5 rows of taxi_header_skipped:")
print(taxi_header_skipped[:5])

print("\nShape of taxi_header_removed:", removed_shape)
print("Shape of taxi_header_skipped:", skipped_shape)

## 3. Boolean Arrays ##

a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])

a_bool = a < 3
b_bool = b == "blue"
c_bool = c > 100

print(a_bool)
print(b_bool)
print(c_bool)

## 4. Boolean Indexing with 1D ndarrays ##

pickup_month = taxi[:, 1]

january_bool = pickup_month == 1
january = pickup_month[january_bool]
january_rides = january.shape[0]
print(january_rides)

february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]
print(february_rides)

## 5. Boolean Indexing with 2D Ndarrays ##

tip_amount = taxi[:,12]
tip_bool = tip_amount > 20
top_tips = taxi[tip_bool, 5:14]

## 6. Assigning Values in Ndarrays ##

# this creates a copy of our taxi ndarray
taxi_copy = taxi.copy()

taxi_copy[1066,5] = 1

taxi_copy[:,0] = 16

taxi_copy[550:552,7] = taxi_copy[:,7].mean()
rows_550_551 = taxi_copy[550:552]

## 7. Assignment Using Boolean Arrays ##

# this creates a copy of our taxi ndarray
taxi_copy = taxi.copy()

trip_length = taxi_copy[:,8]
trip_length[trip_length < 60] = 0

## 8. Assignment Using Boolean Arrays (Continued) ##

# create a new array filled with `0`
zeros = np.zeros([taxi.shape[0], 1])
# append the array to the taxi data to create a new column
taxi_modified = np.concatenate([taxi, zeros], axis=1)
# inspect the last five columns of the first ten rows
print(taxi_modified[:10, -5:])

taxi_modified[taxi_modified[:,6] == 2, 15] = 1
taxi_modified[taxi_modified[:,6] == 3, 15] = 1
taxi_modified[taxi_modified[:,6] == 5, 15] = 1

## 9. Challenge: Which Is the Busiest Airport? ##

jfk = taxi[taxi[:,5] == 2,]
jfk_count = jfk.shape[0]
print(jfk_count)

laguardia = taxi[taxi[:,5] == 3,]
laguardia_count = laguardia.shape[0]
print(laguardia_count)

newark = taxi[taxi[:,5] == 5,]
newark_count = newark.shape[0]
print(newark_count)

busiest_airport = "laguardia"

## 10. Challenge: Calculating Statistics for Trips on Clean Data ##

trip_distance = taxi[:, 7] # trip distance in miles
trip_length = taxi[:, 8] / 3600 # trip length in hours
trip_mph = trip_distance / trip_length # average trip speed in mph

cleaned_taxi = taxi[trip_mph < 100]

mean_distance = cleaned_taxi[:,7].mean()
mean_length = cleaned_taxi[:,8].mean()
mean_total_amount = cleaned_taxi[:,13].mean()

[[      nan       nan       nan ...       nan       nan       nan]
 [2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]
(2014, 15)
First 5 rows of taxi_header_removed:
[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
  1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
  2.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
 

### 2.3 Introduction to Pandas

In [1]:
## 2. Introduction to the Data ##

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
f500 = pd.read_csv("/content/drive/MyDrive/Data/f500.csv", index_col=0)
f500.index.name = None

f500_type = type(f500)
f500_shape = f500.shape
print(f500_type)
print(f500_shape)

## 3. Introducing DataFrames ##

f500_top_6 = f500.head(6)
f500_bottom_8 = f500.tail(8)

## 4. Introducing DataFrames (Continued) ##

f500.info()

float64_dtype = 3
int64_dtype = 7
object_dtype = 6

## 5. Selecting a Column from a DataFrame by Label ##

industries = f500["industry"]
industries_type = type(industries)
print(industries)
print(industries_type)

## 7. Selecting Columns from a DataFrame by Label (Continued) ##

countries = f500["country"]
revenues_years = f500[["revenues", "years_on_global_500_list"]]
ceo_to_sector = f500.loc[:,"ceo":"sector"]
print(countries)

## 8. Selecting Rows from a DataFrame by Label ##

toyota = f500.loc["Toyota Motor"]
drink_companies = f500.loc[["Anheuser-Busch InBev", "Coca-Cola", "Heineken Holding"]]
middle_companies = f500["Tata Motors":"Nationwide"]
print(toyota)

## 10. Value Counts Method ##

countries = f500["country"]
country_counts = countries.value_counts()
top_country = "USA"

hq_locations = f500["hq_location"]
hql_counts = hq_locations.value_counts()
top_hq_city = "Beijing, China"

## 11. Selecting Items from a Series by Label ##

countries = f500["country"]
country_counts = countries.value_counts()
india = country_counts["India"]
north_america = country_counts[["USA", "Canada", "Mexico"]]
japan_to_spain = country_counts["Japan":"Spain"]
print(type(japan_to_spain))

## 12. Summary Challenge ##

big_movers = f500.loc[["Aviva" , "HP" , "JD.com" , "BHP Billiton"] , ["rank" , "previous_rank"]]
bottom_companies = f500.loc["National Grid":"AutoNation", ["rank", "sector", "country"]]
revenue_giants = f500.loc[["Apple", "Industrial & Commercial Bank of China", "China Construction Bank", "Agricultural Bank of China"] , "revenues":"profit_change"]

Mounted at /content/drive
<class 'pandas.core.frame.DataFrame'>
(500, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   rank                      500 non-null    int64  
 1   revenues                  500 non-null    int64  
 2   revenue_change            498 non-null    float64
 3   profits                   499 non-null    float64
 4   assets                    500 non-null    int64  
 5   profit_change             436 non-null    float64
 6   ceo                       500 non-null    object 
 7   industry                  500 non-null    object 
 8   sector                    500 non-null    object 
 9   previous_rank             500 non-null    int64  
 10  country                   500 non-null    object 
 11  hq_location               500 non-null    object 
 12  website                   500 non-null

### 2.4 Exploring Data with Pandas : Fundamentals

In [4]:
## 1. Introduction to the Data ##

f500_head = f500.head(10)
f500.info()

## 2. Vectorized Operations ##

rank_change = f500["previous_rank"] - f500["rank"]

## 3. Series Data Exploration Methods ##

rank_change =  f500["previous_rank"] - f500["rank"]
rank_change_max = rank_change.max()
rank_change_min = rank_change.min()

## 4. Series Describe Method ##

rank = f500["rank"]
rank_desc = rank.describe()
prev_rank = f500["previous_rank"]
prev_rank_desc = prev_rank.describe()

## 5. Method Chaining ##

zero_previous_rank = f500["previous_rank"].value_counts().loc[0]

## 6. Dataframe Exploration Methods ##

max_f500 = f500.max(numeric_only = "True")

## 7. Dataframe Describe Method ##

f500_desc = f500.describe()

## 8. Assignment with pandas ##

f500.loc["Dow Chemical", "ceo"] = "Jim Fitterling"

## 9. Using Boolean Indexing with pandas Objects ##

motor_bool = f500["industry"] == "Motor Vehicles and Parts"
motor_countries = f500.loc[motor_bool, "country"]

## 10. Using Boolean Arrays to Assign Values ##

import numpy as np
prev_rank_before = f500["previous_rank"].value_counts(dropna=False).head()
f500.loc[f500["previous_rank"] == 0, "previous_rank"] = np.nan

prev_rank_after = f500["previous_rank"].value_counts(dropna=False).head()

## 11. Creating New Columns ##

f500["rank_change"] = f500["previous_rank"] - f500["rank"]
rank_change_desc = f500["rank_change"].describe()

## 12. Challenge: Top Performers by Country ##

industry_usa_bool = f500[f500["country"] == "USA"]
industry_usa = industry_usa_bool["industry"].value_counts().head(2)
print(industry_usa)
sector_china_bool = f500[f500["country"] == "China"]
sector_china = sector_china_bool["sector"].value_counts().head(3)
print(sector_china)

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   rank                      500 non-null    int64  
 1   revenues                  500 non-null    int64  
 2   revenue_change            498 non-null    float64
 3   profits                   499 non-null    float64
 4   assets                    500 non-null    int64  
 5   profit_change             436 non-null    float64
 6   ceo                       500 non-null    object 
 7   industry                  500 non-null    object 
 8   sector                    500 non-null    object 
 9   previous_rank             500 non-null    int64  
 10  country                   500 non-null    object 
 11  hq_location               500 non-null    object 
 12  website                   500 non-null    object 
 13  years_on_global_500_list  500 non-null    int64  
 14  em

### 2.5 Exploring Data with Pandas: Intermediate

In [7]:
## 1. Introduction ##

import pandas as pd
import numpy as np

# read the dataset into a pandas dataframe
f500 = pd.read_csv("/content/drive/MyDrive/Data/f500.csv", index_col=0)
f500.index.name = None

# replace 0 values in the "previous_rank" column with NaN
f500.loc[f500["previous_rank"] == 0, "previous_rank"] = np.nan

f500_selection = f500[["rank", "revenues", "revenue_change"]].head()

## 2. Reading CSV Files with pandas ##

f500 = pd.read_csv("/content/drive/MyDrive/Data/f500.csv")
f500.index.name = "Company"
f500.columns.name = "Metric"
f500.loc[f500["previous_rank"] == 0, "previous_rank"] = np.nan

## 3. Using iloc to Select by Integer Location ##

fifth_row = f500.iloc[4]
company_value = f500.iloc[0,0]

## 4. Using iloc to Select by Integer Location (Continued) ##

first_three_rows = f500[0:3]
first_seventh_row_slice = f500.iloc[[0, 6], 0:5]

## 5. Using pandas Methods to Create Boolean Masks ##

prev_rank_null = f500["previous_rank"].isnull()
null_prev_rank = f500[prev_rank_null][["company","rank","previous_rank"]]

## 6. Working with Integer Labels ##

prev_rank_is_null = f500[f500["previous_rank"].isnull()]
top5_null_prev_rank = prev_rank_is_null.iloc[0:5]

## 7. Pandas Index Alignment ##

profited = f500[f500["profits"].notnull()]
costs = profited["revenues"] - profited["profits"]
f500["costs"] = costs

## 8. Using Boolean Operators ##

large_revenue = f500["revenues"] > 100000
negative_profits = f500["profits"] < 0
combined = large_revenue & negative_profits
big_rev_neg_profit = f500.loc[combined,:]

## 9. Using Boolean Operators (Continued) ##

brazil_venezuela = f500[(f500["country"] == "Brazil") | (f500["country"] == "Venezuela")]
tech_outside_usa = f500[(f500["sector"] == "Technology") & ~(f500["country"] == "USA")].head()

## 10. Sorting Values ##

selected_rows = f500[f500["country"] == "Japan"]
sorted_rows = selected_rows.sort_values("profits", ascending=False)
top_japanese_company = sorted_rows.iloc[0][["company","profits"]]
print(top_japanese_company)

## 11. Using Loops with pandas ##

top_employer_by_country = {}

# Create an array of unique values from the country column
countries = f500["country"].unique()

for c in countries:
    # Select only the rows that have a country name equal to the current iteration
    selected_rows = f500[f500["country"] == c]

    # Sort those rows by the employees column in descending order
    sorted_rows = selected_rows.sort_values("employees", ascending=False)

    # Select the first row from the sorted dataframe
    first = sorted_rows.iloc[0]

    # Extract the company name from the company column of the first row
    top_employer = first["company"]

    # Assign the results to the top_employer_by_country dictionary
    top_employer_by_country[c] = top_employer

## 12. Challenge: Calculating Return on Assets by Sector ##

f500["roa"] = f500["profits"] / f500["assets"]

top_roa_by_sector = {}

sectors = f500["sector"].unique()

for s in sectors:
    selected_rows = f500[f500["sector"] == s]
    sorted_rows = selected_rows.sort_values("roa", ascending=False)
    first = sorted_rows.iloc[0]
    top_roa = first["company"]
    top_roa_by_sector[s] = top_roa

Metric
company    Toyota Motor
profits         16899.3
Name: 4, dtype: object


### 2.6 Data Cleaning Basics

In [4]:
## 1. Reading CSV Files with Encodings ##

from google.colab import drive
#drive.mount('/content/drive')

import pandas as pd

laptops = pd.read_csv("/content/drive/MyDrive/Data/laptops.csv", encoding="latin1")
print(laptops.info())

## 2. Cleaning Column Names ##

new_columns = []

for c in laptops.columns:
    c = c.strip()
    new_columns.append(c)

laptops.columns = new_columns

## 3. Cleaning Column Names (Continued) ##

def clean_col(col):
    col = col.strip()
    col = col.replace("Operating System","os")
    col = col.replace(" ","_")
    col = col.replace("(","")
    col = col.replace(")","")
    col = col.lower()
    return col

new_columns = []
for c in laptops.columns:
    c = clean_col(c)
    new_columns.append(c)

laptops.columns = new_columns

## 4. Converting String Columns to Numeric ##

unique_ram = laptops["ram"].unique()
print(unique_ram)

## 5. Removing Non-Digit Characters ##

laptops["screen_size"] = laptops["screen_size"].str.replace('"', '')
laptops["ram"] = laptops["ram"].replace('GB','')

## 6. Converting Columns to Numeric dtypes ##

laptops["screen_size"] = laptops["screen_size"].astype(float)
#laptops["ram"] = laptops["ram"].astype(int)
print(laptops["ram"].unique())
print("`ram` dtype:", laptops["ram"].dtype)

## 7. Renaming Columns ##

laptops.rename({"screen_size": "screen_size_inches"}, axis=1, inplace=True)
laptops.rename({"ram": "ram_gb"}, axis=1, inplace=True)
ram_gb_desc = laptops["ram_gb"].describe()
print(ram_gb_desc)

## 8. Extracting Values from Strings ##

gpu_split = laptops["gpu"].str.split()
laptops["gpu_manufacturer"] = gpu_split.str[0]
gpu_manufacturer_counts = laptops["gpu_manufacturer"].value_counts()
laptops["cpu_manufacturer"] = laptops["cpu"].str.split().str[0]
cpu_manufacturer_counts = laptops["cpu_manufacturer"].value_counts()

## 9. Correcting Bad Values ##

print(laptops["os"].unique())
mapping_dict = {"macOS" : "macOS", "No OS" : "No OS", "Windows" : "Windows", "Mac OS" : "macOS", "Linux" : "Linux", "Android" : "Android", "Chrome OS" : "Chrome OS"}
laptops["os"] = laptops["os"].map(mapping_dict)
print(laptops["os"].value_counts())

## 10. Dropping Missing Values ##

laptops_no_null_rows = laptops.dropna()
laptops_no_null_cols = laptops.dropna(axis=1)

## 11. Filling Missing Values ##

value_counts_before = laptops.loc[laptops["os_version"].isnull(), "os"].value_counts()
laptops.loc[laptops["os"] == "macOS", "os_version"] = "X"
laptops.loc[laptops["os"] == "No OS", "os_version"] = "Not Applicable"
value_counts_after = laptops.loc[laptops["os_version"].isnull(), "os"].value_counts()

## 12. Challenge: Clean a String Column ##

weight_unique = laptops["weight"].unique()
laptops["weight"] = laptops["weight"].str.replace("kgs","")
laptops["weight"] = laptops["weight"].str.replace("kg","")
laptops["weight"] = laptops["weight"].astype(float)
laptops.rename({"weight": "weight_kg"}, axis=1, inplace=True)
#laptops.to_csv('/tmp/laptops_cleaned.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Manufacturer              1303 non-null   object
 1   Model Name                1303 non-null   object
 2   Category                  1303 non-null   object
 3   Screen Size               1303 non-null   object
 4   Screen                    1303 non-null   object
 5   CPU                       1303 non-null   object
 6   RAM                       1303 non-null   object
 7    Storage                  1303 non-null   object
 8   GPU                       1303 non-null   object
 9   Operating System          1303 non-null   object
 10  Operating System Version  1133 non-null   object
 11  Weight                    1303 non-null   object
 12  Price (Euros)             1303 non-null   object
dtypes: object(13)
memory usage: 132.5+ KB
None
['8GB' '16GB' '4GB' '2GB' '12GB' '6

## 3. Guided Project: Exploring eBay Car Sales Data

See project here : ["Project_Pandas"](https://colab.research.google.com/drive/1RQQ4SYa_uFOal4hYBpMHK77Mj_78kHz0)

## 5. Conclusion
- Ce que j’ai appris :

  *   Comment la vectorisation accélère notre code
  *   Les tableaux à n dimensions et les ndarrays de NumPy
  *   Comment sélectionner des éléments spécifiques, des lignes, des colonnes, des tranches 1D et des tranches 2D à partir de ndarrays
  *   Comment appliquer des calculs simples à des tableaux entiers
  *   Comment la diffusion permet d'effectuer des opérations entre des ndarrays de formes différentes
  *   Comment utiliser des méthodes vectorisées pour effectuer des calculs sur l'un ou l'autre axe des ndarrays

  *   A utiliser `numpy.genfromtxt()` pour charger des données dans un ndarray
  *   Les valeurs NaN et la manière dont elles peuvent affecter les données
  *   Les tableaux booléens et comment les créer à l'aide d'opérateurs de comparaison
  *   A utiliser l'indexation booléenne pour filtrer les valeurs dans les ndarrays unidimensionnels et bidimensionnels
  *   L'attribution de nouvelles valeurs à un ndarray en fonction de leurs emplacements
  *   L'attribution de nouvelles valeurs à un ndarray en fonction de leurs valeurs, à l'aide de l'indexation booléenne

  *   Comment sélectionner des données à partir d'objets pandas à l'aide de tableaux booléens
  *   Comment attribuer des données à l'aide d'étiquettes et de tableaux booléens
  *   Comment créer de nouvelles colonnes dans pandas
  *   De nombreuses nouvelles méthodes pour faciliter l’analyse des données dans Pandas

  *   A sélectionner des colonnes, des lignes et des éléments individuels en utilisant leur emplacement entier
  *   A utiliser `pd.read_csv()` pour lire les fichiers CSV dans pandas
  *   A travailler avec des étiquettes d'axes entiers
  *   A utiliser les méthodes pandas pour produire des tableaux booléens
  *   A utiliser des opérateurs booléens pour combiner des comparaisons booléennes afin d'effectuer des sélections plus complexes
  *   A utiliser des étiquettes d’index pour aligner les données
  *   A utiliser l'agrégation pour effectuer une analyse avancée à l'aide d'une boucle for


- Références : [Introduction to Pandas and NumPy for Data Analysis](https://www.dataquest.io/course/pandas-fundamentals/).